config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  resources :lists do
    resources :bookmarks, only: [:new, :create]
    member do
      resources :comments, only: [:new, :create]
    end
  end

  resources :movies, only: [:index, :show] do
    resources :bookmarks, only: [:new, :create] do
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :list_id, uniqueness: { scope: :movie_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :list

  validates :comment, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id]) if params[:list_id]
    @movie = Movie.find(params[:movie_id]) if params[:movie_id]
  end

  def create
    if params[:list_id]
      @list = List.find(params[:list_id])
      @bookmark = Bookmark.new(bookmark_params)
      @bookmark.list = @list
    else
      @movie = Movie.find(params[:movie_id])
      @bookmark = Bookmark.new(bookmark_params)
      @bookmark.movie = @movie
    end

    if @bookmark.save
      redirect_to list_path(@list) if @list
      redirect_to list_path(@bookmark.list_id) if @movie
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ActionController::Base

  def create
    @comment = Comment.new(comment_params)
    @list = List.find(params[:id])
    @comment.list_id = @list.id

    if @comment.save
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity, layout: 'application'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_lists, only: [ :index ]
  before_action :set_list, only: [ :show ]

  def index
  end

  def new
    @list = List.new
  end

  def show
    @comment = Comment.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render action: "new"
    end
  end

  private

  def set_lists
    @lists = List.all
  end

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def stars_rating(value)
    value = value / 2.0
    full_stars = value.floor
    half_stars = 0
    remainder = ((value - full_stars)*2).round()
    if remainder == 2
      full_stars += 1
    elsif remainder == 1
      half_stars = 1
    end
    return {full_stars: full_stars, half_stars: half_stars}
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@movie || @list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <% if @movie.present? %>
    <%= f.association :list %>
  <% else %>
    <%= f.association :movie %>
  <% end %>
  <%= f.button :submit, class:'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>



  <body>

<header>
    <div class="px-3 py-2 text-bg-dark border-bottom">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <%= image_tag "tv.png", alt: "My movie lists", width: 50 %>
          </a>
          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <%= link_to new_list_path, class:"nav-link text-white" do %>
                <i class="fa-solid fa-film"></i>
                New list
              <% end %>
            </li>
            <li>
              <%= link_to movies_path, class:"nav-link text-white" do %>
                <i class="fa-solid fa-film"></i>
                All movies
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </header>
  <div class="container mt-5">
    <%= yield %>
  </div>

  <div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">© 2023 Pontus movies, Inc</p>
  </footer>
</div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="shadow-lg movies-jumbotron rounded-4 row align-items-center p-5">
  <div class="col-md-6 flex-wrap">
    <h2 class="text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit</h2>
    <p class="text-secondary">Sed do eiusmod tempor incididunt ut labore et dolore magna</p>
    <%= link_to 'Create your list', new_list_path, class:'btn btn-primary btn-lg' %>
  </div>
</div>


<div class="row mt-5">
  <%  @lists.each do |list| %>
  <div class="col-md-4">
    <div class="card">
      <%= cl_image_tag list.photo.key, crop: :fill %>
      <div class="card-body">
        <h5 class="card-title"><%= list.name %></h5>
        <p class="card-text">This list has: <%= list.movies.count %> movies</p>
      </div>
      <div class="card-body border-top">
        <%= link_to 'View', list_path(list), class:'btn btn-primary w-100' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name, label: 'Name your list', error: 'List name is mandatory, please specify one' %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class:'btn btn-primary' %>
  <a class="btn btn-outline-primary" href="/">Go back</a>
<% end %>

app/views/lists/show.html.erb
<div class="row flex-row align-items-center">
    <div class="col-md-6">
    <span class="px-2 py-1 bg-light border rounded-5">Last updated: <%= @list.updated_at.strftime("%Y-%m-%d") %></span>
      <h2 class="my-3"><%= @list.name %></h2>
      <%= link_to 'Add a movie', new_list_bookmark_path(@list), class:"btn btn-primary" %>
      <a href="#comments" class="btn btn-outline-primary">Add a comment</a>
    </div>
  <div class="col-md-6 py-5 d-flex justify-content-center">
    <%= cl_image_tag @list.photo.key, height: 400, width: 600, crop: :fill, class:'rounded-5 shadow-sm' %>
  </div>
</div>

<div class="row border-bottom mb-5 border mb-5 bg-light p-5">
<% @list.movies.each do |movie| %>

<div class="col-md-3 mb-5">
  <div class="card shadow-sm">

    <%= image_tag "https://image.tmdb.org/t/p/w500/#{movie.poster_url}", class:'card-img-top' %>

    <div class="card-body" style="height: 150px;">

      <h5 class="card-title"><%= movie.title %></h5>
      <% if movie.overview.length > 100 %>
        <p class="card-title"><%= movie.overview[0,100]%>...</p>

      <% else %>
        <p class="card-title"><%= movie.overview %></p>
      <% end %>

    </div>

    <div class="card-footer">
      <div class="card-body">
        <% stars = stars_rating(movie.rating.to_i)  %>
        <p>
          <% stars[:full_stars].times do |i| %>
            <i class="fa-solid fa-star"></i>
          <% end %>
          <% stars[:half_stars].times do |i| %>
            <i class="fa-solid fa-star-half"></i>
          <% end %>
        </p>
        <% movie_comment = @list.bookmarks.where(list_id: @list.id, movie_id: movie.id).first.comment %>
        <span class="text-muted">"<%= movie_comment %>"</span>
      </div>
    </div>


  </div>

</div>
<% end %>

</div>

      <h4 id="comments">What do you think about this list?</h4>
      <%= simple_form_for @comment do |f| %>
        <%= f.input :comment, label: 'What is your comment?', class:"bg-primary" %>
        <%= f.button :submit, class:'btn btn-outline-primary' %>
      <% end %>

      <% if @list.comments.length > 0 %>
        <h4 class="mt-5">Comments</h4>
        <div class="row">
          <% @list.comments.all.each do |comment| %>
            <div class="col-md-3">
              <div class="card bg-light">
              <div class="card-body"><%= comment.comment %></div>
              </div>
            </div>
          <% end %>
      </div>
      <% else %>
      <h4 class="mt-5">No comments yet...</h4>
      <% end %>

app/views/movies/index.html.erb
<div class="row">
<% @movies.each_with_index do |movie, index| %>


  <div class="col-lg-3 mb-5">
  <%= link_to "?#{movie.id}", 'data-bs-toggle':"modal", 'data-bs-target':"#exampleModal#{index}" do %>
      <div class="card movie-card-hover-animation">
        <%= image_tag "https://image.tmdb.org/t/p/w500/#{movie.poster_url}" %>
        <card-body>
        </card-body>
      </div>
  <% end %>
    </div>

  <!-- Modal -->
<div class="modal fade" id="exampleModal<%=index%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"><%= movie.title %></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= movie.overview %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= link_to 'Add movie to a list', new_movie_bookmark_path(movie), class:'btn btn-primary'%>
      </div>
    </div>
  </div>
</div>

<% end %>

  </div>